baseURL = 'https://kelceygibbons.com/'
languageCode = 'en-us'
title = 'Kelcey Gibbons | MIT Historian'
theme = "personal"

[params]
siteTitle = "Kelcey Gibbons"
siteSubtitle = "Historian of Technology / MIT"

homeImg = "images/podium.jpeg"
homeTag1 = "PhD Candidate @ MIT"
homeTag2 = "Professional Daydreamer"
homeSlogan = "Learning is Liberating"
homeText = "Hi! I study American histories of technology by focusing on African American education and professionalization."

[[menu.main]]
name = 'home'
pageRef = '/'
weight = 5

[[menu.main]]
name = 'about'
pageRef = '/about'
weight = 10

[[menu.main]]
name = 'cv'
pageRef = '/cv'
weight = 20

[[menu.main]]
name = 'Poems & Stories'
pageRef = '/writing'
weight = 30
